### ISSUE TITLE
Requires authentication

### ISSUE THREAD

**Issue by greenbigfrog** [ihoru/todoist_bot#1]
Always prompts asking to get authentication

**Comment by Hydro8** [comment]
Here too

**Comment by 5fth** [comment]
Yes, same for me.

**Comment by specter119** [comment]
Same for me

**Comment by TejasAvinashShetty** [comment]
same for me.
 Ubuntu 16 telegram version 1.7

**Comment by jace** [comment]
Came here for the same problem. Every interaction re-requests authentication.

**Comment by dmnc-net** [comment]
Hi folks, adding :+1: to the OP is better than "same here" comments. And for making this one useful, I'm adding the screenshot :)
![image](https://user-images.githubusercontent.com/2069874/67572157-ee02d080-f735-11e9-946c-f75b3b2150e1.png)

**Comment by ihoru** [comment]
Fixed, folks!

I'm so ashamed that I couldn't find those 3 hours to fix this and some other problems in the project.
Mostly because I stopped using it by myself. But also because It worked for me from the begining (by some strange occasion for my user all data was saved correctly)

I hope someone may find the bot useful.

**Comment by TejasAvinashShetty** [comment]
Thank you. Happy new year

**Comment by jace** [comment]
Seems like the bot is down. Sending it `/start` is showing me a red exclamation in Telegram. Message not delivered.
